config/routes.rb
ProductCatalogue::Application.routes.draw do
  resources :products, only: [:index, :new, :create, :destroy] do
    post 'import', on: :collection
  end
  root 'products#index'
end

app/models/product.rb
class Product < ActiveRecord::Base
  after_create :created
  mount_uploader :photo, ProductPhotoUploader
  validates_presence_of :name, :price

  def created
    self.sku = name.upcase.gsub(/[^A-Z]/, '')[0..4] + sprintf("%05d", id)
    save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
require 'csv'
require 'open-uri'

class ProductsController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "itsasecre7", except: [:index]
  respond_to :html

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    product_params = params.require(:product).permit(:name, :price)
    @product = Product.create(product_params)
    flash[:notice] = "Product was successfully created." if @product.persisted?
    respond_with @product, location: products_url
  end

  def destroy
    @product = Product.destroy(params[:id])
    flash[:notice] = "Product was successfully destroyed." unless @product.persisted?
    respond_with @product, location: products_url
  end

  def import
    products = []
    p params[:product]
    CSV.foreach(params[:product][:file].path, headers: true) do |row|
# todo clean up
      product = Product.new(
        name:  row['name'],
        price: row['price'],
      )
			product.photo = open(row['thumbnail_url']) if row['thumbnail_url'].present?
      if !product.save
        flash[:warning] = "Could not save product! #{product.errors.messages}"
    		# render :status => 422, :html => "bad product" and return
        redirect_to products_url
      end
      products << product
    end
    if params[:product][:notify]
      ImportResultMailer.result_email(products).deliver
    end
    flash[:notice] = "Success! Imported #{params[:product][:file].original_filename}"
    redirect_to products_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProductCatalogue</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash[:notice] %>
  <div style="background:#9f9; padding:20px; font-size:1.4em;">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:warning] %>
  <div style="background:#f99; padding:20px; font-size:1.4em;">
    <%= flash[:warning] %>
  </div>
<% end %>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<p><%= link_to 'New Product', new_product_path %></p>

<table>
  <thead>
    <tr>
      <th>Sku</th>
      <th>Name</th>
      <th>Price</th>
      <th>Photo</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.sku %></td>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= link_to('Photo', product.photo.preview.url, :"data-featherlight" => 'image') if product.photo.present? %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<p><%= link_to 'Back', products_path %></p>

<section>
  <h1>Import Products</h1>
  <%= form_for @product, url: import_products_path, html: {multipart: true} do |f| %>
    <%= f.file_field :file %>
    <p><%= f.check_box :notify, :checked => true, :style => "display:inline;" %> Notify admin?</p>
    <%= f.submit :import %>
  <% end %>
</section>

<section>
  <h1>New product</h1>
  <%= render 'form' %>
</section>